#!/usr/bin/env python
#define type of people based on age

age = int(input("Your age: "));
if age > 0 and age < 13:
    print("You are a child.")
elif age >= 13 and age <= 19:
    print("You are a teenager.")
elif age > 19:
    print("You are an adult.")
else:
    print("incorrect input")
